"""add verification tier saved searches

Revision ID: 433050083e91
Revises: 9a7ae942240c
Create Date: 2026-07-26 23:46:39.637941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '433050083e91'
down_revision: Union[str, None] = '9a7ae942240c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('q', sa.String(length=255), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('verified_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recruiter_profiles', sa.Column('verification_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recruiter_profiles', sa.Column('tier', sa.String(length=20), server_default='free', nullable=False))
    op.add_column('talent_profiles', sa.Column('tier', sa.String(length=20), server_default='free', nullable=False))
    op.add_column('talent_profiles', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('talent_profiles', sa.Column('verification_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_profiles', 'verification_requested_at')
    op.drop_column('talent_profiles', 'is_verified')
    op.drop_column('talent_profiles', 'tier')
    op.drop_column('recruiter_profiles', 'tier')
    op.drop_column('recruiter_profiles', 'verification_requested_at')
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
