"""add social links audition brief submission url

Revision ID: 7b2ebb625db8
Revises: 433050083e91
Create Date: 2026-07-27 01:21:14.328998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b2ebb625db8'
down_revision: Union[str, None] = '433050083e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('submission_url', sa.String(length=500), nullable=True))
    op.add_column('casting_calls', sa.Column('audition_brief', sa.Text(), nullable=True))
    op.add_column('casting_calls', sa.Column('audition_reference_url', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('tiktok_url', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('youtube_url', sa.String(length=500), nullable=True))
    op.add_column('talent_profiles', sa.Column('website_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_profiles', 'website_url')
    op.drop_column('talent_profiles', 'youtube_url')
    op.drop_column('talent_profiles', 'twitter_url')
    op.drop_column('talent_profiles', 'tiktok_url')
    op.drop_column('talent_profiles', 'facebook_url')
    op.drop_column('talent_profiles', 'instagram_url')
    op.drop_column('casting_calls', 'audition_reference_url')
    op.drop_column('casting_calls', 'audition_brief')
    op.drop_column('applications', 'submission_url')
    # ### end Alembic commands ###
