"""add saved talents

Revision ID: 7e3dc8549f5e
Revises: cdeda5d5d6ba
Create Date: 2026-07-25 08:23:22.547356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e3dc8549f5e'
down_revision: Union[str, None] = 'cdeda5d5d6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_talents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('talent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talent_id'], ['talent_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recruiter_id', 'talent_id', name='uq_saved_talent_recruiter_talent')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_talents')
    # ### end Alembic commands ###
