"""add email verification and job alert preference

Revision ID: 8339d883c8cc
Revises: f4a2c9b7e1d3
Create Date: 2026-07-27 20:36:11.040793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8339d883c8cc'
down_revision: Union[str, None] = 'f4a2c9b7e1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent_profiles', sa.Column('job_alert_emails', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_expires_at')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'email_verified')
    op.drop_column('talent_profiles', 'job_alert_emails')
    # ### end Alembic commands ###
