"""general skills pivot

Revision ID: 8b613a1320cb
Revises: 7e3dc8549f5e
Create Date: 2026-07-25 08:45:32.037897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8b613a1320cb'
down_revision: Union[str, None] = '7e3dc8549f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casting_calls', 'category',
               existing_type=postgresql.ENUM('ACTOR', 'MODEL', 'SINGER', 'DANCER', 'PHOTOGRAPHER', 'STYLIST', 'WRITER', 'DESIGNER', 'OTHER', name='talent_category'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('media', sa.Column('title', sa.String(length=255), nullable=True))
    op.alter_column('media', 'media_type',
               existing_type=postgresql.ENUM('PHOTO', 'VIDEO', name='media_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('talent_profiles', sa.Column('skills', sa.ARRAY(sa.String(length=60)), nullable=True))
    op.alter_column('talent_profiles', 'category',
               existing_type=postgresql.ENUM('ACTOR', 'MODEL', 'SINGER', 'DANCER', 'PHOTOGRAPHER', 'STYLIST', 'WRITER', 'DESIGNER', 'OTHER', name='talent_category'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('talent_profiles', 'height_cm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent_profiles', sa.Column('height_cm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('talent_profiles', 'category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTOR', 'MODEL', 'SINGER', 'DANCER', 'PHOTOGRAPHER', 'STYLIST', 'WRITER', 'DESIGNER', 'OTHER', name='talent_category'),
               existing_nullable=False)
    op.drop_column('talent_profiles', 'skills')
    op.alter_column('media', 'media_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PHOTO', 'VIDEO', name='media_type'),
               existing_nullable=False)
    op.drop_column('media', 'title')
    op.alter_column('casting_calls', 'category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTOR', 'MODEL', 'SINGER', 'DANCER', 'PHOTOGRAPHER', 'STYLIST', 'WRITER', 'DESIGNER', 'OTHER', name='talent_category'),
               existing_nullable=False)
    # ### end Alembic commands ###
