"""add attributes and credits

Revision ID: aa5f8b3f4b67
Revises: 7b2ebb625db8
Create Date: 2026-07-27 06:09:53.846031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aa5f8b3f4b67'
down_revision: Union[str, None] = '7b2ebb625db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talent_profile_id', sa.UUID(), nullable=False),
    sa.Column('project_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('company_or_director', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('date_label', sa.String(length=50), nullable=True),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['talent_profile_id'], ['talent_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('talent_profiles', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_profiles', 'attributes')
    op.drop_table('credits')
    # ### end Alembic commands ###
