"""add invitations and intro video url

Revision ID: e31afc91dfcc
Revises: aa5f8b3f4b67
Create Date: 2026-07-27 12:28:43.419669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e31afc91dfcc'
down_revision: Union[str, None] = 'aa5f8b3f4b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('casting_call_id', sa.UUID(), nullable=False),
    sa.Column('talent_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['casting_call_id'], ['casting_calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talent_id'], ['talent_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('casting_call_id', 'talent_id', name='uq_invitation_casting_call_talent')
    )
    op.add_column('talent_profiles', sa.Column('intro_video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent_profiles', 'intro_video_url')
    op.drop_table('invitations')
    # ### end Alembic commands ###
